### ISSUE TITLE
Hide twitter & reddit tokens in environ

### ISSUE THREAD

**Issue by imjakedaniels** [imjakedaniels/animated_leafs_graphs#18]
**WHAT IS IT?**
Removing hard-coded tokens by calling them from my local environment.

**WHY AM I DOING IT?**
To increase privacy of my tokens and best practices.

**WHEN IS IT DONE?**
When PR is merged.

**TASKS**
- [x] Add Twitter to .Renviron
- [x] Add Reddit to .Renviron
- [x] Confirm `Sys.getenv()` will convert to python with {reticulate}
- [x] Update comment

**FUTURE NOTES**
- N/A
