### ISSUE TITLE
Automating period-by-period charts

### ISSUE THREAD

**Issue by imjakedaniels** [imjakedaniels/animated_leafs_graphs#21]
**WHAT IS IT?**
A hands-free script that posts three times every game. Each post is post-period chatter chart. Will utilize 1-minute intervals for more granularity as well as variance from the final product. Will not include goals or scoreboard because they are too unreliable.

**WHY AM I DOING IT?**
Triple my content for those sweet engagement numbers!

**WHEN IS IT DONE?**
When it passes a live-test. Script can then be merged.

**TASKS**
- [ ] Explore reliable trigger options:
   - [ ] Stream tweets on MapleLeafs account for "1st period" and such
   - [ ] Look for other post-period accounts
   - [ ] Consider if tweeting my own triggers out of ChatterCharts to mark period end is too demanding.
- [ ] Adjust script for 1-minute intervals
- [ ] Remove scoreboard/goals
- [ ] Add flair to differentiate from regular charts

**FUTURE NOTES**
- Unknown how to trigger – reliability is a major issue
- Might cause brand fatigue
- Probably best to hand-tailor interesting periods, but I can't handle that upkeep
