### ISSUE TITLE
Shadowtext testing

### ISSUE THREAD

**Issue by imjakedaniels** [imjakedaniels/animated_leafs_graphs#22]
**WHAT IS IT?**
Visual improvement to the moving text and/or scoreboard.

**WHY AM I DOING IT?**
The text is kinda flat. Shadowtext would add depth. Could also be used for #20 to add social theme elements.

**WHEN IS IT DONE?**
When PR is merged to Master

**TASKS**
- [ ] Test features:
   - [ ] White text, blue bg shadowtext on dynamic text
   - [ ] Shadowtext on scoreboard
- [ ] Update script
- [ ] Merge to master

**FUTURE NOTES**
This might help with #20
