### ISSUE TITLE
Re-structure for scaling

### ISSUE THREAD

**Issue by imjakedaniels** [imjakedaniels/animated_leafs_graphs#23]
**WHAT IS IT?**
A total rebuild of the project so I just need to control inputs at the top of the page and run once.

**WHY AM I DOING IT?**
It makes my life easier. There are only a few things left to tweak each time now. By removing some automation, I can make it simple for non-R users to participate. And will scale better as the backbone to other opportunities for Chatter Charts.

**WHEN IS IT DONE?**
When I've merged a PR with a satisfactory version to the repo.

**TASKS**
- [ ] Place all variables to top
- [ ] Remove the regex for social media
- [ ] Schedule to scrape tweets 30-minutes after game and store in csv.
- [ ] Create a csv with team-related themes (Primary/Secondary colours for Hockey, Basketball, Football & social hashtags/keywords)
- [ ] Create a job script

**FUTURE NOTES**
Design it where it isn't Maple Leafs dependent. It can be the Raptors too. Or Patriots. So the team social media account is a required input. Home team events, away team events are optional. 

Mass scheduling to scrape tweets would be beneficial. Can be done manually still.

```r
sport == "Hockey"
game_start <- "2020-07-10 20:00:00" 
social_media == "@MapleLeafs" | "http//gamethread.com" # if str_detect(social media, "http") source(reddit_script.py)
home_team_event <- c("219049012481098")
away_team_event ,- c("")
unwanted_words <- c("list")
min_threshold <- 3
```

Notebook should only show data.frame of the `full_twitter_df` for modifying.
Job is everything + rendering.

**Comment by imjakedaniels** [comment]
Scraping 30-minutes after the game seems... interesting. Because how do I know when it's done? Or do I give it a 2h hour window after the average end?

4PM game ends at 6:30PM, get data at 8:30PM, run script and post by 9PM
7PM game ends at 9:30PM, get data at 11:30PM, run script Post by Midnight.

I think it's safe to auto-scrape with 2 hour buffer and post the charts the next day.

**Comment by imjakedaniels** [comment]
Issue of scraping would be rate-limiting. Would need to investigate how many apps I can use before I scale.
