### ISSUE TITLE
Live Score update

### ISSUE THREAD

**Issue by imjakedaniels** [imjakedaniels/animated_leafs_graphs#8]
**WHAT IS IT?**
New feature to uptick the score whenever a` created_at` passes a `leafs_goals` or `opponent_goals`.

**WHY AM I DOING IT?**
Because it would explain what the lines are without explaination.

**WHEN IS IT DONE?**
When a PR is merged to Master

**TASKS**
- [x] Create running score column in animated_df
- [x] str_glue them into the caption
- [x] Finalize code (with real timeline data)
- [ ] Comment/Clean code

**FUTURE NOTES**
- Probably do this in the chart's background.
- Scrape Leafs Timeline so i can finalize code

**Comment by imjakedaniels** [comment]
0
0 GOAL
1
1 GOAL
2
2 GOAL
3
3
3
3
3
3
